# my_string=(8, 9, 190)
# list1=list(my_string)
# print(list1)

s = 'shrubbery123'
d1=["strawberry"]
l=list(s)
# d="".join(l)
# l.append(1)
# print(l)
# print("l is:",l)
# d="".join(l)
# print("d1 is:", d1)
l.extend(d1)
print(l)
res="".join(l)
print(l)
print(res)
res2="".join(res)
print(res2)
